/**
 * ============================================================
 * FOODHUBBIE SAAS — Bot Command Listener
 * ============================================================
 * Listens for commands from the Admin Dashboard at:
 * bot/{businessId}/{outletId}/commands
 */

const { db, resolvePath, getData } = require('./firebase');
const { formatJid } = require('../shared/utils');

/**
 * Initializes the command listener.
 */
function initCommandListener(sock) {
  const path = resolvePath('botCommands'); // businesses/{bid}/outlets/{oid}/botCommands
  console.log(`[Commands] Listening for triggers at: ${path}`);

  const cmdRef = db.ref(path);
  
  cmdRef.on('child_added', async (snap) => {
    const cmd = snap.val();
    if (!cmd) return;

    console.log(`[Commands] Received: ${cmd.action}`);

    try {
      switch (cmd.action) {
        case "SEND_GENERIC_MESSAGE":
          if (cmd.phone && cmd.message) {
            const jid = formatJid(cmd.phone);
            await sock.sendMessage(jid, { text: cmd.message });
          }
          break;

        case "SEND_DAILY_REPORT":
          await handleDailyReport(sock, cmd);
          break;
          
        // Add more commands as needed
      }

      // Always remove command after processing
      await snap.ref.remove();
    } catch (err) {
      console.error(`[Commands] Failed to execute ${cmd.action}:`, err.message);
    }
  });
}

/**
 * Generates and sends a detailed sales report
 */
async function handleDailyReport(sock, cmd) {
  const targetDate = cmd.targetDate || new Date().toISOString().split('T')[0];
  console.log(`[Reports] Generating report for ${targetDate}...`);

  const ordersPath = resolvePath('orders');
  const storeSettings = await getData('settings/Store');
  const adminPhone = storeSettings?.reportPhone;

  if (!adminPhone) {
    console.warn("[Reports] No reportPhone found in settings. Cannot send report.");
    return;
  }

  const orders = await getData('orders') || {};
  const dailyOrders = Object.values(orders).filter(o => {
    const orderDate = (o.createdAt || "").split('T')[0];
    return orderDate === targetDate && o.status !== "Cancelled";
  });

  if (dailyOrders.length === 0) {
    const jid = formatJid(adminPhone);
    await sock.sendMessage(jid, { text: `📊 *SALES REPORT: ${targetDate}*\n━━━━━━━━━━━━━━━━━━━━\nNo orders found for this date.` });
    return;
  }

  let totalRevenue = 0;
  let totalOrders = dailyOrders.length;
  let itemStats = {};

  dailyOrders.forEach(o => {
    totalRevenue += Number(o.total || 0);
    const items = Array.isArray(o.cart) ? o.cart : (Array.isArray(o.items) ? o.items : []);
    items.forEach(i => {
      const key = `${i.name || i.item} (${i.size || 'N/A'})`;
      itemStats[key] = (itemStats[key] || 0) + (i.qty || i.quantity || 1);
    });
  });

  // Sort top items
  const sortedItems = Object.entries(itemStats).sort((a, b) => b[1] - a[1]).slice(0, 5);

  let msg = `📊 *DAILY SALES REPORT* 🚀\n`;
  msg += `📅 *Date:* ${targetDate}\n`;
  msg += `🏢 *Outlet:* ${storeSettings?.storeName || 'Outlet'}\n`;
  msg += `━━━━━━━━━━━━━━━━━━━━\n\n`;
  msg += `📈 *Total Orders:* ${totalOrders}\n`;
  msg += `💰 *Total Revenue:* ₹${totalRevenue.toLocaleString()}\n\n`;
  
  msg += `🍕 *Top Selling Items:*\n`;
  sortedItems.forEach(([name, qty]) => {
    msg += `• ${name}: ${qty}\n`;
  });

  msg += `\n━━━━━━━━━━━━━━━━━━━━\n`;
  msg += `_Generated by Foodhubbie Bot_`;

  const adminJid = formatJid(adminPhone);
  await sock.sendMessage(adminJid, { text: msg });
  console.log(`[Reports] Report sent to ${adminPhone}`);
}

module.exports = {
  initCommandListener
};
